language: python
python: 
  - "3.9.1"
services:
  - postgresql
env:
  - DJANGO=3.1.4 DB=postgres
global:
  - PGPORT=5432
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
      - postgresql-13-postgis-3.1
before_install:
  - cd Corrige
install:
  - pip install -r requirements.txt
before_script:
  - cp ./Corrige/settings.py ./Corrige/local_settings.py
  - export PATH="/usr/lib/postgresql/13/bin:$PATH"
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "CREATE USER Kelsier WITH PASSWORD 'Kelsier'"
  - psql -U postgres -c "ALTER USER Kelsier SUPERUSER"
  - psql -U postgres -c "CREATE DATABASE corrige OWNER Kelsier"
  - python manage.py makemigrations
  - python manage.py migrate

branches:
  only:
    - master
    - dev
    - feat/s2/Configurar-proyecto
