En este apartado hablaremos que los gastos de la realización de todo el proyecto, ya sea documentación, reuniones o desarrollo de la aplicación. Empezaremos con la parte más cuantiosa, que son los salarios, después especificaremos apartados menos costosos y terminaremos con los costes totales, que separaremos en teórico y real.

El proyecto está estimado en **300 horas** de trabajo por persona, basándonos en los 12 créditos del Trabajo Fin de Grado. Por lo tanto, el proyecto supondrá un coste temporal inicial de **600 horas**. Además, los dos miembros del equipo tienen el mismo puesto.

==== Salarios
Suponemos que cada miembro cobra unos **8,5 euros la hora**, basándonos en salarios de puestos reales. Por lo que 300 horas sumarán un coste de **2550 euros**. También supondremos un **35%** de costes de la Seguridad Social. Estos costes deberían ser calculado mensualmente, así que su coste real, que supondría un incremento entre 30 y 35%. Escogemos el más alto. Además, asumiremos que ha habido un sobrecoste por costes por formación, es decir, costes que se han producido al dedicar tiempo en cubrir falta de conocimiento en el desarrollo. Valoramos este sobrecoste del **10%** del **salario total**. Desglosaremos este coste en la **Tabla 9**.

.Salarios
[grid=cols]
|===
|Costes por hora (€/hora) |Salario total (€) |Coste de formación (€) |Coste de la Seguridad Social (€) | Coste total por persona (€) | Coste total de la empresa (€)

| 8,5
| 2550
| 510
| 892,5
| 3442,5
| 6885

|===

==== Amortizaciones
Una amortización es una sucesión de pagos para saldar el coste de bienes físicos para el funcionamiento de la empresa. Lo único que tendríamos que amortizar son los dos ordenadores que suponen un coste total de **2000 euros**. Este tipo de elemento se permite amortizar un **20%** anualmente. Se desglosará en la **Tabla 10**.

.Amortizaciones
[grid=cols]
|===
|Valor total (€) |Coste 2020 (€) |Coste 2021 (€) | Coste total (€) 

| 2000
| 400
| 400
| 800

|===

==== Licencias
Esta serán las versiones de pago de servicios digitales. La única licencia que hemos utilizado es Photoshop que cuesta **24,19 euros al mes** y que hemos utilizado durante 5 meses. Lo resumiremos en la **Tabla 11**.

.Licencias
[grid=cols]
|===
|Coste (€/mes) |Coste total (€)

| 24,19
| 120,95

|===

==== Servicios en la nube
Estos son servidores que dan servicio a través de Internet. Para el despliegue se utilizado la versión _Hobby_ de Heroku, que cuesta **7 dólares**, que son unos **5,74 euros**. Se ha utilizado durante 5 meses. Lo resumiremos en la **Tabla 12**.

.Despliegue
[grid=cols]
|===
|Coste (€/mes) |Coste total (€)

| 5,74
| 28,7

|===

==== Coste teórico total
Reuniendo los datos mencionados en los apartados anteriores podemos resumir los costes en la **Tabla 13**.

.Coste total
[grid=cols]
|===
|Salarios (€) |Amortizaciones (€) |Licencias (€) |Servicios en la nube (€) |Coste total (€)

| 6885
| 800
| 120,95
| 28,7
| 7834,65

|===

==== Coste real total
Aunque se planificó inicialmente una inversión de 600 horas en el proyecto, se han producido una leve desviación del **X%** en la realización del proyecto que aumentará el coste en salarios. Esta desviación la podemos atribuir a los xref:Retrasos e incidencias[retrasos e incidencias] que se han producido en el proyecto. Concretaremos este sobrecoste en la **Tabla 14**.

.Coste real
[grid=cols]
|===
|Coste en salarios teóricos (€) |Coste en salarios reales (€) |Coste teórico total (€) |Coste real total (€)

| 6885
| 
| 7834,65
| 

|===
