A continuaci칩n hablaremos de la fuente escogida y de d칩nde hemos seleccionado las imagenes mostradas en la aplicaci칩n.

==== Fuente 
La opci칩n a la hora de seleccionar una fuente ha sido seleccionado con el fin de evitarnos problemas jur칤dicos, as칤 como, poderla usar en aplicaciones de fines lucatrivos. 

===== Elecci칩n

Nos decantamos por la Fuente Ubuntu, la cual obtuvimos del siguiente link:

https://design.ubuntu.com/font/

La licencia de esta fuente es copyleft permite que las tipograf칤as sean 춺usadas, estudiadas, modificadas y redistribuidas libremente췉 cumpliendo los t칠rminos estipulados en ella.

La documentaci칩n de la licencia se encuentra en la carpeta fonts, cuyo nombre es "LICENSE.txt".

==== Im치genes

La opci칩n a la hora de seleccionar las im치genes para la web fue dificil, ya que busc치bamos un banco de im치genes que nos permitiera el uso comercial pensando en un hipot칠tica uso de la misma y sin derechos de autor.

===== Elecci칩n

Nos decantamos por la web https://unsplash.com/, la cual tiene un gran n칰mero de im치genes muy 칰tiles, y una licencia que nos permit칤a lo nombrado anteriormente.

Con respecto a la licencia, dice lo siguiente:

_Unsplash photos are made to be used freely. Our license reflects that._

* _All photos can be downloaded and used for free._
* _Commercial and non-commercial purposes._
* _No permission needed (though attribution is appreciated!)._

_What is not permitted 游녩_

* _Photos cannot be sold without significant modification._
* _Compiling photos from Unsplash to replicate a similar or competing service._

Para m치s informaci칩n puede consultar dicha licencia en el siguiente enlace:
https://unsplash.com/license