Este apartado es una parte crucial a la hora de trabajar en grupo con un software. En nuestro caso hemos usado Git, el cual es una gran herramienta que se basa en la creación de ramas para el trabajo en paralelo. 

Algo muy importante a la hora de trabajar con Git es llevar una metodología, nosotros hemos usado la más conocida por parte de ambos, GitFlow. Esto ha dado lugar a una mejora del  desarrollo continuo de las prácticas.

Dividiremos este apartado en tres con el fin de desglosar de manera más detallada los mismos: Gestión de ramas, Gestión de commits y Pull requests
 
==== Gestión de ramas

Hemos sido muy estrictos en este apartado, en el cual hemos seguido las siguientes pautas.

Tenemos dos Ramas por defecto:

* master
* dev

En la rama **dev** se incluirán todas las ramas de desarrollo con *pull requests*. La rama **master** solo se podrán añadir desde la rama **dev**, para incluir la release. 

El resto de ramas seguirán el siguiente esquema: 

*<codigo_rama>/<codigo_sprint>/<nombre_tarea>*

Códigos de rama (<codigo_rama>):

* feat/     (nueva feature)
* fix/      (bug fix)
* hotfix/   (bug fixes en producción)
* refactor/ (refactorización de código)
* docs/     (cambios de documentación)
* test/     (añadir o refactorizar tests)
* release/  (nueva release)

Cógigos de sprint (<codigo_sprint>):

* s0            (previo al comienzo del desarrollo de código)
* s1/s2/s3/s4   (sprints 1, 2, 3, 4 respectivamente)
* d             (tras la finalización del desarrollo, realización de memoria)

Nombre de las tareas (<nombre_tarea>): Nombre especificado en Jira, o abreviación. Por ejemplo, CU-07 Edición de profesores, o simplemente, CU-07. Se pueden añadir varias tareas separadas por &.

==== Gestión de commits

El comando git commit se basa en guardar todos los cambios realizados en local junto a una breve descripción del usuario con el fin de dar sentido al trabajo realizado.

Los commits deben seguir el siguiente patrón: *[<tipo_commit>] <nombre_commit>*. Además se puede añadir una descripción opcionalmente.

Tipo de commit (<tipo_commit>):

* feat      (nueva feature)
* fix       (bug fix)
* refactor  (refactorización de código)
* doc       (cambios de documentación)
* test      (añadir o refactorizar tests)
* release   (nueva release)

==== Pull requests

Para añadir funcionalidad a la rama *dev* se abrirá una pull request. Esto se basa en hacer una petición de la tarea realizada, con el fin de añadirla a el proyecto. El que haya desarrollado la funcionalidad se asignará a la pull request y asignará al compañero como revisor. Para que la pull request se de como válida debe de pasar el control y análisis de Travis y Sonarcloud, además del visto bueno del revisor. 

Una vez que se haya hecho merge a dev, la rama se eliminará.