= Gestión de código

== Gestión de ramas
Ramas por defecto:
- master
- dev

En la rama **dev** se incluirán todas las ramas de desarrollo con *pull requests*. La rama **master** solo se podrán añadir desde la rama **dev**, para incluir la release. 

El resto de ramas seguirán el siguiente esquema:
*<codigo_rama>/<codigo_sprint>/<nombre_tarea>*

Códigos de rama (<codigo_rama>):

* feat/     (nueva feature)
* fix/      (bug fix)
* hotfix/   (bug fixes en producción)
* refactor/ (refactorización de código)
* docs/     (cambios de documentación)
* test/     (añadir o refactorizar tests)
* release/  (nueva release)

Cógigos de sprint (<codigo_sprint>):

* s0            (previo al comienzo del desarrollo de código)
* s1/s2/s3/s4   (sprints 1, 2, 3, 4 respectivamente)
* sd            (tras la finalización del desarrollo, realización de memoria)

Nombre de las tareas (<nombre_tarea>): Nombre especificado en Jira, o abreviación. Por ejemplo, CU-07 Edición de profesores, o simplemente, CU-07. Se pueden añadir varias tareas separadas por &.

== Gestión de commits
Los commits deben seguir el siguiente patrón: [<tipo_commit>] <nombre_commit>. Además se puede añadir una descripción opcionalmente.

Tipo de commit (<tipo_commit>):

* feat      (nueva feature)
* fix       (bug fix)
* refactor  (refactorización de código)
* doc       (cambios de documentación)
* test      (añadir o refactorizar tests)
* release   (nueva release)

== Pull requests
Para añadir funcionalidad a la rama *dev* se abrirá una pull request. El que haya desarrollado la funcionalidad se asignará a la pull request y asignará al compañero como revisor. Para que la pull request se de como válida debe de pasar el control y análisis de Travis y Sonarcloud, además del visto bueno del revisor. 