=  Nombre
:toc:
:toc-title: Índice general

== Resumen

== Índice de figuras

== Índice de cuadros

== Índice de código o algoritmos

== I. Definición de objetivos

Los objetivos del proyecto son:

* Desarrollar una aplicación web que permita dar funcionalidad a los profesores inscritos para la correcta evaluación mediante competencias.

* Posibilitar la utlización de la aplicación
 para todos los niveles de la enseñanza.

* Implementar distintos métodos de cáculo para la evaluación y no dificultar el desarrollo de otros posibles métodos.

* Permitir utilizar la aplicación para el sistema de evaluación tradicional.

* Crear una interfaz simple que permita utilizar la aplicación de forma intuitiva.

* Permitir la correcta visualización en distintas pantallas de sobremesa y alguna de móvil sin perder funcionalidad.

* Internacionalizar la aplicación para que esté disponible en español e inglés.

== II. Análisis de antecedentes y aportación realizada

== III. Análisis temporal y de costes de desarrollo

=== Planificación

=== Retrasos e Incidencias

=== Reuniones

=== Costes

== IV. Análisis de requisitos, diseño e implementación

=== Diagramas

=== Mockups

=== Requisitos

=== Casos de uso

=== Justificaciones de las tecnologías y herramientas utilizadas

=== Gestión de código

=== Gestión de versiones

=== Fuentes e Imágenes

=== Implementación del cálculo

=== Responsive

=== Traducción

=== Instalación

== V. Manual de usuario

== VI. Pruebas

== VII. Comparativas con otras alternativas

== VIII. Conclusiones y desarrollos futuros

== Glosario

* **Actividad**: Tarea que crea un profesor para evaluar una o varias competencias de un alumno. Pueden ser pruebas, exámenes, ejercicios de clases, salidas extraescolares, trabajos grupales, etc.
* **Competencia concreta**: Competencia de nivel 1. Competencia muy delimitada, asociada a una asignatura, que se puede puntuar directamente.
* **Competencia específica**: Competencia de nivel 2. Competencia estrechamente relacionada con una asignatura. Se calcula a partir de las competencias concretas.
* **Competencia general**: Competencia de nivel 3. Competencia de alto nivel que engloba varias asignaturas y habilidades.
* **Ejercicio**: Parte de la que se componen las actividades. Por ejemplo, en un exámen de matemáticas, puede ser que un ejercicio sea realizar una ecuación.
* **Grupo**: Conjunto de alumnos asignados a una asignatura de un nivel específico. Por ejemplo, una clase de 3ºB de matemáticas. 

=== Casos prácticos de competencias

[grid=cols]
|===
|Niveles |Nombre en la aplicación |Enseñanza primaria/ESO/Bachillerato |Títulos universitarios 

| Nivel 1
| Competencias concretas
| Estándares de aprendizaje
| Criterios del profesor

| Nivel 2
| Competencias específicas
| Criterios de evaluación
| Competencias generales y específicas

| Nivel 3
| Competencias generales
| Competencias clave
| Competencias básicas

|===


== Bibliografía

* https://www.boe.es/diario_boe/txt.php?id=BOE-A-2014-2222
* https://www.boe.es/boe/dias/2020/12/30/pdfs/BOE-A-2020-17264.pdf
* https://www.us.es/estudiar/que-estudiar/oferta-de-grados/grado-en-ingenieria-informatica-ingenieria-del-software
* https://www.us.es/estudiar/que-estudiar/oferta-de-grados/grado-en-pedagogia
* http://www.juntadeandalucia.es/educacion/descargasrecursos/curriculo-primaria/pdf/PDF/textocompleto.pdf
* https://www.boe.es/diario_boe/txt.php?id=BOE-A-2015-37