=== Pruebas de automáticas
En el desarrollo no se ha realizado pruebas automáticas dado que necesitan una mayor inversión de tiempo que las pruebas manuales, las cuales cumplen su función correctamente. Además no es lo suficientemente grande y complejo para necesitar la automatización de las pruebas. Hemos visto más importante invertir el tiempo en el desarrollo que en implementar pruebas automáticas.

=== Pruebas de formulario

Un tipo de prueba muy común en el mundo del software son las pruebas de los formulario. Estos son un apartado crucial de las aplicaciones puesto que envian los datos directamente a la base de datos. Esto tiene un peligro, y es que si un usuario introduce un dato incorrecto podría llegar a destruir o corromper la base de datos de la aplicación web.

Con estas pruebas nos hemos asegurado que este tipo de peligros no sucedan en nuestra aplicación. Para ello hemos realizado las siguientes pruebas manuales:

* Comprobamos que la vista este correctamente traducida.
* Verificamos la obligatoriedad de los campos enviandolo completamente vacío y rellenando uno a uno, comprobando si se muestra el mensaje de obligatoriedad.
* Comprobamos las restricciones de modelo, tanto longuitud como rango, y vemos si se muestra el error correspondiente. Esto se hace en ambos idiomas.
* Lo enviamos correctamente y verificamos si se creado o modificado y que lleva a la vista correspondiente.
* Comprobamos si el botón de _Volver_ lleva a la vista correspondiente.
* Verificamos que no se puede acceder al formulario si no tienes permiso (**GET**).
* Comprobamos si cambiando la url del formulario no se puede crear o modificar sin permiso (**POST**).
* Comprobamos el _reponsive_.

=== Pruebas de borrado

En este apartado hemos intentado que ningún usuario pueda realizar esta acción sin los permisos correspondientes. También hemos comprobado la función de dichos métodos.

Con estas pruebas nos hemos asegurado que lo nombrado anteriormente esté correcto. Para ello hemos realizado las siguientes pruebas manuales:

* Comprobamos que la vista este correctamente traducida.
* Comprobamos si el botón de _Volver_ lleva a la vista correspondiente.
* Lo enviamos correctamente y verificamos si se borrado y que lleva a la vista correspondiente.
* Verificamos que no se puede acceder a la opción de borrar si no tienes permiso (**GET**).
* Comprobamos si cambiando la url del formulario no se puede borrar sin permiso (**POST**).
* Comprobamos el _reponsive_.

=== Pruebas de listado

En el apartado de listados hemos intentado asegurar que los usuarios sin permisos para poder ver los mismos no pudieran hacerlo. También hemos comprobado el formato y vista correcta de los listados de la aplicación.

Para ello hemos realizado las siguientes pruebas manuales:

* Comprobamos que la vista este correctamente traducida.
* Comprobamos que la vista este correctamente traducida.
* Comprobamos que no se pueda acceder a un listado sin permiso mediante url.
* Comprobamos si el botón de _Volver_ lleva a la vista correspondiente.
* Comprobamos el _reponsive_.