
Gracias a la estrategia que hemos comentado en el apartado de xref:Planificación[Planificación] hemos podido mantener los retrasos al mínimo, siendo el desvío grave un total de tres días. También han surgido una serie de incidencias que se han solventado a lo largo del desarrollo. A lo largo de esta sección concretamos cuales son estos retrasos (Véase Tabla 5) e incidencias (Véase Tabla 6).

==== Retrasos

En la **Tabla 5** veremos la lista de los retrasos que ha surgido en el proyecto con sus respectivas fechas de su finalización teórica y la real. Los retrasos más graves a nuestro parecer han sido los acontecidos en los despliegues de las versiones 0.1 y 0.4, que no ha permitido la correspondiente revisión por parte del tutor en la fecha prevista. En resto de retrasos han sido de una gravedad muy baja dado que no ha retrasado otras tareas.

.Tabla de retrasos de desarrollo
[grid=cols]
[cols=3*,options="header"]
|===
| Tarea
| Fecha prevista
| Fecha realizada

| CU-02 Creación de alumnos.
| 5 de Enero
| 7 de Enero

| CU-09 Listado de Grupos de clase.
| 16 de Enero
| 17 de Enero

| Despliegue de la versión 0.1.
| 25 de Enero
| 28 de Enero

| Replanificación. 
| 27 de Enero
| 28 de Enero

| Despliegue versión 0.4. 
| 27 de Abril
| 29 de Abril
|===

==== Incidencias

En la **Tabla 6** observaremos la lista de incidencias que hemos tenido a lo largo del proyecto. Las incidencias más graves han sido la falta del _CRUD_ de evaluaciones con anterioridad, lo que nos ha provocado tener que replanificar la dos primera semanas del _Sprint_ 2, y la identificación de un par de fallos al asignar y desasignar competencias, que retrasó el despliegue de la versión 0.4.

.Tabla de incidencias
[grid=cols]
[cols=2*,options="header"]
|===
|Tarea
|Fecha de la incidencia

| Añadir CRUD de evaluaciones.
| 28 de Enero

| Reordenación casos de uso.
| 28 de Enero

| Error al mostrar botones de la barra de navegación.
| 26 de Febrero

| Error al copiar los ejercicios.
| 19 de Marzo

| Error al ocultar botones al copiar.
| 25 de Marzo

| Error de selección de nivel para los cálculos de evaluación por competencias.
| 16 de Abril

| Error de selección de nivel para los cálculos de evaluación por competencias.
| 16 de Abril

| Error 404 de fuente.
| 19 de Abril

| Error de actualización de tipo de evaluación.
| 22 de Abril

| Error de cálculo de la nota de un ejercicio.
| 22 de Abril

| Error de intervalo de nota.
| 22 de Abril

| Error al asignar una competencia.
| 27 de Abril

| Error al desasignar una competencia.
| 27 de Abril
|===