# Generated by Django 3.1.4 on 2021-01-17 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_parent', to='corrigeapp.competence'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='subject_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='subject_weight'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='weight'),
        ),
    ]
