# Generated by Django 3.1.4 on 2021-04-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence_mark',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_competence_mark', to='corrigeapp.exercise'),
            preserve_default=False,
        ),
    ]
