# Generated by Django 3.1.4 on 2021-03-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation_mark',
            name='manual_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='manual_mark'),
        ),
        migrations.AlterField(
            model_name='evaluation_mark',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='mark'),
        ),
    ]
