# Generated by Django 3.1.4 on 2021-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='parent',
        ),
        migrations.AddField(
            model_name='competence',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='_competence_parent_+', to='corrigeapp.Competence', verbose_name='competences_parent'),
        ),
    ]
