# Generated by Django 3.1.4 on 2021-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0002_auto_20210117_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=300, verbose_name='name'),
        ),
    ]
