# Generated by Django 3.1.4 on 2021-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0002_auto_20210315_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_mark',
            name='evaluation_type',
            field=models.CharField(default=1, max_length=50, verbose_name='evaluation_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competence_mark',
            name='evaluation_type',
            field=models.CharField(default='text', max_length=50, verbose_name='evaluation_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise_mark',
            name='evaluation_type',
            field=models.CharField(default='text', max_length=50, verbose_name='evaluation_type'),
            preserve_default=False,
        ),
    ]
