# Generated by Django 3.1.4 on 2021-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0002_auto_20210219_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_competence_parent_+', to='corrigeapp.Competence', verbose_name='competences_parent'),
        ),
    ]
