# Generated by Django 3.1.4 on 2021-01-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0004_auto_20210117_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_parent', to='corrigeapp.evaluation'),
        ),
    ]
