# Generated by Django 3.1.4 on 2021-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0004_auto_20210315_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='text', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
