# Generated by Django 3.1.4 on 2021-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0004_auto_20210406_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='evaluation_type_final',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='evaluation_type_final'),
        ),
        migrations.AlterField(
            model_name='set',
            name='evaluation_type_partial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='evaluation_type_partial'),
        ),
    ]
