# Generated by Django 3.1.6 on 2021-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0006_competence_subject_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weight'),
        ),
    ]
