# Generated by Django 3.1.6 on 2021-04-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0007_auto_20210424_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='statement',
            field=models.CharField(max_length=300, verbose_name='statement'),
        ),
    ]
