# Generated by Django 3.1.6 on 2021-04-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrigeapp', '0008_auto_20210425_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='subject_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='subject_weight'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='exercise_competence',
            name='intensity',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='intensity'),
        ),
        migrations.AlterField(
            model_name='exercise_competence',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weight'),
        ),
    ]
